# Generated by Django 5.0.1 on 2024-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="nome")),
                ("birth_date", models.DateField(verbose_name="data de nascimento")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("N", "Não binário"),
                        ],
                        max_length=1,
                        verbose_name="gênero",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=128, null=True, verbose_name="endereço"
                    ),
                ),
                ("email", models.EmailField(max_length=32, null=True)),
                ("phone", models.CharField(max_length=16, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_purchase_date", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("G", "Em dia"), ("Y", "Mensal"), ("R", "Devedor")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
