# Generated by Django 5.0.1 on 2024-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_options_alter_client_last_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("G", "Em dia"), ("Y", "Mensal"), ("R", "Devedor")],
                max_length=1,
                null=True,
            ),
        ),
    ]
