# Generated by Django 5.0.6 on 2024-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('modified_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
